[package]
name = "sugoi-lt-obs-screen"
version = "0.1.0"
authors = ["approvers"]
license = ""
repository = ""
default-run = "sugoi-lt-obs-screen"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "0.11", features = [ "event" ] }

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "sugoi-lt-obs-screen"
path = "src/main.rs"
