name: Check
on:
  push:

permissions:
  contents: read

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - run: pnpm run lint

  tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./src/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 libayatana-appindicator3-dev libsoup2.4

      - run: cargo fmt --all -- --check
        working-directory: src-tauri
      - run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: src-tauri
