name: Check
on:
  push:

permissions:
  contents: read

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - run: pnpm run lint

  tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      # based on https://github.com/tauri-apps/tauri-action#testing-the-build
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - run: cargo fmt --all -- --check
        working-directory: src-tauri
      - run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: src-tauri
